global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: 
          - 'backend:8000'
          - 'backend1:8000'
          - 'backend2:8000'
          - 'backend3:8000'
          - 'backend4:8000'
          - 'backend5:8000'