global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend1'
    static_configs:
      - targets:
          - 'backend1:8000'

  - job_name: 'backend2'
    static_configs:
      - targets:
          - 'backend2:8000'
